apiVersion: v1
kind: Service
metadata:
  name: stress-test-app
  namespace: stress-test-tool
spec:
  selector:
    app: stress-test-app
  ports:
    - name: backend
      port: 3000
      targetPort: 3000
    - name: frontend
      port: 5173
      targetPort: 5173
  type: ClusterIP
